[package]
name = "sunscreen_gpu_runtime"
version = "0.10.0"
edition = "2024"
authors = ["Sunscreen"]
rust-version = "1.87.0"
license = "AGPL-3.0-only"
description = "This crate GPU support for Sunscreen's Torus FHE (TFHE) implementation"
homepage = "https://sunscreen.tech"
repository = "https://github.com/Sunscreen-tech/spf"
documentation = "https://docs.sunscreen.tech"
keywords = ["FHE", "TFHE", "lattice", "cryptography"]
categories = ["cryptography"]

[dependencies]
bytemuck = { workspace = true }
cuda-driver-sys = { workspace = true, optional = true }
cuda-runtime-sys = { workspace = true, optional = true }
serde = { workspace = true }
thiserror = { workspace = true }

[build-dependencies]
find_cuda_helper = { workspace = true, optional = true }

[features]
default = [] #["cuda"]
test_kernels = []
cuda = ["gpu", "dep:find_cuda_helper", "dep:cuda-runtime-sys", "dep:cuda-driver-sys"]
amdhip = ["gpu"]
gpu = []

[[bin]]
name = "device_info"
required_features = ["gpu"]